# Generated by Django 5.0.14 on 2025-05-09 16:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='متن کامنت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('status', models.CharField(choices=[('approved', 'تایید شده'), ('pending', 'در انتظار تایید'), ('rejected', 'رد شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='تعداد لایک')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'کامنت',
                'verbose_name_plural': 'کامنت\u200cها',
                'ordering': ['-created_at'],
            },
        ),
    ]
