# Generated by Django 5.0.14 on 2025-05-09 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام مکان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('location', models.CharField(max_length=255, verbose_name='لوکیشن جغرافیایی')),
                ('score', models.FloatField(default=0, verbose_name='امتیاز')),
                ('type', models.CharField(max_length=100, verbose_name='نوع مکان')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='تعداد بازدید')),
            ],
            options={
                'verbose_name': 'مکان',
                'verbose_name_plural': 'مکان\u200cها',
            },
        ),
        migrations.CreateModel(
            name='PlaceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='place_images/', verbose_name='عکس مکان')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Place.place')),
            ],
            options={
                'verbose_name': 'عکس مکان',
                'verbose_name_plural': 'عکس\u200cهای مکان',
            },
        ),
    ]
