# Generated by Django 5.0.14 on 2025-05-09 19:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Place', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='city',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='شهر   '),
            preserve_default=False,
        ),
    ]
