# Generated by Django 5.0.14 on 2025-05-30 02:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Place', '0002_place_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='Cost',
            field=models.CharField(choices=[('low', 'کم'), ('medium', 'متوسط'), ('high', 'زیاد')], default=django.utils.timezone.now, max_length=10, verbose_name='بودجه'),
            preserve_default=False,
        ),
    ]
