# Generated by Django 5.0.14 on 2025-05-30 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Place', '0003_place_cost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={},
        ),
        migrations.AlterModelOptions(
            name='placeimage',
            options={},
        ),
    ]
