# Generated by Django 5.0.14 on 2025-05-09 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget', models.CharField(choices=[('low', 'کم'), ('medium', 'متوسط'), ('high', 'زیاد')], max_length=10, verbose_name='بودجه')),
                ('people_count', models.PositiveIntegerField(verbose_name='تعداد افراد')),
                ('distance', models.FloatField(verbose_name='مسافت (کیلومتر)')),
                ('trip_type', models.CharField(max_length=100, verbose_name='نوع سفر')),
                ('places_of_interest', models.TextField(verbose_name='علاقه\u200cمندی\u200cها')),
                ('places_per_day', models.PositiveIntegerField(default=1, verbose_name='تعداد مکان در روز')),
            ],
            options={
                'verbose_name': 'سفر',
                'verbose_name_plural': 'سفرها',
            },
        ),
    ]
