# Generated by Django 5.0.14 on 2025-05-29 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0002_tripplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripplan',
            name='end_date',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='tripplan',
            name='start_date',
            field=models.CharField(max_length=11),
        ),
    ]
