# Generated by Django 5.0.14 on 2025-05-30 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0003_alter_tripplan_end_date_alter_tripplan_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('canceled', 'لغو شده'), ('running', 'در حال انجام'), ('finished', 'پایان یافته')], default='running', max_length=10, verbose_name='وضعیت سفر'),
        ),
    ]
