# Generated by Django 5.0.14 on 2025-05-09 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام هتل')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('score', models.FloatField(default=0, verbose_name='امتیاز')),
                ('stars', models.PositiveSmallIntegerField(default=1, verbose_name='تعداد ستاره\u200cها')),
                ('tariff_type', models.CharField(max_length=100, verbose_name='نوع تعرفه')),
            ],
            options={
                'verbose_name': 'هتل',
                'verbose_name_plural': 'هتل\u200cها',
            },
        ),
        migrations.CreateModel(
            name='HotelImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hotel_images/', verbose_name='عکس هتل')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Hotel.hotel')),
            ],
            options={
                'verbose_name': 'عکس هتل',
                'verbose_name_plural': 'عکس\u200cهای هتل',
            },
        ),
    ]
