# Generated by Django 5.0.14 on 2025-05-30 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام ویژگی')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات ویژگی')),
            ],
            options={
                'verbose_name': 'ویژگی هتل',
                'verbose_name_plural': 'ویژگی\u200cهای هتل',
            },
        ),
        migrations.CreateModel(
            name='HotelRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان قانون')),
                ('description', models.TextField(verbose_name='شرح قانون')),
            ],
            options={
                'verbose_name': 'قانون هتل',
                'verbose_name_plural': 'قوانین هتل',
            },
        ),
        migrations.AddField(
            model_name='hotel',
            name='base_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='قیمت پایه'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True, verbose_name='عرض جغرافیایی'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True, verbose_name='طول جغرافیایی'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='peak_season_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='قیمت فصل شلوغ'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='weekend_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='قیمت آخر هفته'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='tariff_type',
            field=models.CharField(max_length=100, null=True, verbose_name='نوع تعرفه'),
        ),
        migrations.CreateModel(
            name='HotelComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='متن نظر')),
                ('rating', models.PositiveSmallIntegerField(default=5, verbose_name='امتیاز')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('is_approved', models.BooleanField(default=False, verbose_name='تایید شده')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Hotel.hotel', verbose_name='هتل')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'نظر هتل',
                'verbose_name_plural': 'نظرات هتل',
            },
        ),
        migrations.AddField(
            model_name='hotel',
            name='features',
            field=models.ManyToManyField(related_name='hotels', to='Hotel.hotelfeature', verbose_name='ویژگی\u200cها'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='rules',
            field=models.ManyToManyField(related_name='hotels', to='Hotel.hotelrule', verbose_name='قوانین'),
        ),
    ]
