# Generated by Django 5.0.14 on 2025-05-30 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0002_hotelfeature_hotelrule_hotel_base_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='peak_season_price',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='weekend_price',
        ),
        migrations.AddField(
            model_name='hotel',
            name='location',
            field=models.CharField(max_length=255, null=True, verbose_name='لوکیشن جغرافیایی'),
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='features',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='rules',
        ),
        migrations.AddField(
            model_name='hotel',
            name='features',
            field=models.TextField(null=True, verbose_name='ویژگی\u200cها'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='rules',
            field=models.TextField(null=True, verbose_name='قوانین'),
        ),
    ]
