# Generated by Django 5.0.14 on 2025-05-30 09:27

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0003_remove_hotel_latitude_remove_hotel_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='features',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='rules',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='hotelfeature',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
