# Generated by Django 5.0.14 on 2025-05-30 09:28

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0004_alter_hotel_features_alter_hotel_rules_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HotelFeature',
        ),
        migrations.DeleteModel(
            name='HotelRule',
        ),
        migrations.AlterField(
            model_name='hotel',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
