# Generated by Django 5.0.14 on 2025-05-30 14:33

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0005_delete_hotelfeature_delete_hotelrule_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotel',
            options={'ordering': ['-rating', '-stars'], 'verbose_name': 'هتل', 'verbose_name_plural': 'هتل\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='hotelimage',
            options={'verbose_name': 'تصویر هتل', 'verbose_name_plural': 'تصاویر هتل'},
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='base_price',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='features',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='location',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='rules',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='score',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='tariff_type',
        ),
        migrations.AddField(
            model_name='hotel',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='شهر'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotel',
            name='has_gym',
            field=models.BooleanField(default=False, verbose_name='باشگاه ورزشی'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='has_parking',
            field=models.BooleanField(default=False, verbose_name='پارکینگ'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='has_pool',
            field=models.BooleanField(default=False, verbose_name='استخر'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='has_restaurant',
            field=models.BooleanField(default=False, verbose_name='رستوران'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='has_room_service',
            field=models.BooleanField(default=False, verbose_name='سرویس اتاق'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='has_spa',
            field=models.BooleanField(default=False, verbose_name='اسپا'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='has_wifi',
            field=models.BooleanField(default=True, verbose_name='اینترنت'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hotels/', verbose_name='تصویر اصلی'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='price_per_night',
            field=models.DecimalField(decimal_places=0, max_digits=12, null=True, verbose_name='قیمت هر شب'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='امتیاز'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='hotelimage',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='description',
            field=models.TextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='name',
            field=models.CharField(max_length=200, verbose_name='نام هتل'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='stars',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='تعداد ستاره'),
        ),
        migrations.AlterField(
            model_name='hotelimage',
            name='image',
            field=models.ImageField(upload_to='hotels/gallery/'),
        ),
    ]
